<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BuyersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('buyers')->delete();

        \DB::table('buyers')->insert(array (
            0 =>
            array (
                'id' => 1,
                'rank_id' => NULL,
                'buyer_category_id' => 1,
                'orders_count' => 1,
                'name' => 'محمد عبد الله',
                'mobile' => '004234234',
                'email' => 'mohammed@gmail.com',
                'verified' => 1,
                'verification_date' => NULL,
                'license' => NULL,
                'address' => 'جدة',
                'latitude' => NULL,
                'longitude' => NULL,
                'password' => NULL,
                'image_profile' => NULL,
                'whatsapp' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'instagram' => NULL,
                'tiktok' => NULL,
                'remember_token' => '
',
                'status' => 'not_active',
                'created_at' => '2021-12-04 10:06:37',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'rank_id' => NULL,
                'buyer_category_id' => NULL,
                'orders_count' => 0,
                'name' => NULL,
                'mobile' => '+11234512345',
                'email' => 'r.user@gmail.com',
                'verified' => 0,
                'verification_date' => NULL,
                'license' => NULL,
                'address' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'password' => NULL,
                'image_profile' => NULL,
                'whatsapp' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'instagram' => NULL,
                'tiktok' => NULL,
                'remember_token' => NULL,
                'status' => 'active',
                'created_at' => '2022-03-13 14:44:48',
                'updated_at' => '2022-03-13 14:57:19',
                'deleted_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'rank_id' => NULL,
                'buyer_category_id' => NULL,
                'orders_count' => 0,
                'name' => NULL,
                'mobile' => '+12244668822446688',
                'email' => NULL,
                'verified' => 0,
                'verification_date' => NULL,
                'license' => NULL,
                'address' => NULL,
                'latitude' => NULL,
                'longitude' => NULL,
                'password' => NULL,
                'image_profile' => NULL,
                'whatsapp' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'instagram' => NULL,
                'tiktok' => NULL,
                'remember_token' => NULL,
                'status' => 'active',
                'created_at' => '2022-03-13 15:03:30',
                'updated_at' => '2022-03-13 15:03:39',
                'deleted_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'rank_id' => NULL,
                'buyer_category_id' => 1,
                'orders_count' => 0,
                'name' => 'Lamar Ali',
                'mobile' => '+11231230980',
                'email' => 'lamar@gmail.com',
                'verified' => 0,
                'verification_date' => NULL,
                'license' => NULL,
                'address' => NULL,
                'latitude' => '24.233',
                'longitude' => '43.23',
                'password' => NULL,
                'image_profile' => NULL,
                'whatsapp' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'instagram' => NULL,
                'tiktok' => NULL,
                'remember_token' => NULL,
                'status' => 'active',
                'created_at' => '2022-03-13 15:06:07',
                'updated_at' => '2022-03-13 15:46:55',
                'deleted_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'rank_id' => NULL,
                'buyer_category_id' => 2,
                'orders_count' => 0,
                'name' => 'أماني أحمد عابد',
                'mobile' => '+1123456123456',
                'email' => 'lamar@gmail.com',
                'verified' => 0,
                'verification_date' => NULL,
                'license' => NULL,
                'address' => NULL,
                'latitude' => '24.233',
                'longitude' => '43.23',
                'password' => NULL,
                'image_profile' => NULL,
                'whatsapp' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'instagram' => NULL,
                'tiktok' => NULL,
                'remember_token' => NULL,
                'status' => 'active',
                'created_at' => '2022-03-13 15:49:11',
                'updated_at' => '2022-03-13 16:25:13',
                'deleted_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'rank_id' => NULL,
                'buyer_category_id' => 1,
                'orders_count' => 0,
                'name' => 'Lamar Ali',
                'mobile' => '+1223344223344',
                'email' => '44li@gmail.com',
                'verified' => 0,
                'verification_date' => NULL,
                'license' => NULL,
                'address' => NULL,
                'latitude' => '24.233',
                'longitude' => '43.23',
                'password' => NULL,
                'image_profile' => NULL,
                'whatsapp' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'instagram' => NULL,
                'tiktok' => NULL,
                'remember_token' => NULL,
                'status' => 'active',
                'created_at' => '2022-03-13 16:29:54',
                'updated_at' => '2022-03-13 16:30:15',
                'deleted_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'rank_id' => NULL,
                'buyer_category_id' => 3,
                'orders_count' => 0,
                'name' => 'Amany Ahmed',
                'mobile' => '+9701111111111111',
                'email' => 'asdasd@aaa.ps',
                'verified' => 0,
                'verification_date' => NULL,
                'license' => NULL,
                'address' => NULL,
                'latitude' => '24.233',
                'longitude' => '43.23',
                'password' => NULL,
                'image_profile' => NULL,
                'whatsapp' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'instagram' => NULL,
                'tiktok' => NULL,
                'remember_token' => NULL,
                'status' => 'active',
                'created_at' => '2022-03-13 16:45:50',
                'updated_at' => '2022-03-13 16:46:15',
                'deleted_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'rank_id' => NULL,
                'buyer_category_id' => 3,
                'orders_count' => 0,
                'name' => 'Lamar Ali',
                'mobile' => '+111122223333',
                'email' => 'lamar@gmail.com',
                'verified' => 0,
                'verification_date' => NULL,
                'license' => NULL,
                'address' => NULL,
                'latitude' => '24.233',
                'longitude' => '43.23',
                'password' => NULL,
                'image_profile' => NULL,
                'whatsapp' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'instagram' => NULL,
                'tiktok' => NULL,
                'remember_token' => NULL,
                'status' => 'active',
                'created_at' => '2022-04-11 03:25:40',
                'updated_at' => '2022-04-11 03:26:04',
                'deleted_at' => NULL,
            ),
        ));


    }
}
