<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('products')->delete();

        \DB::table('products')->insert(array (
            0 =>
            array (
                'id' => 1,
                'type' => 'offer_request',
                'deal_id' => NULL,
                'seller_id' => 60,
                'main_category_id' => 4,
                'sub_category_id' => 9,
                'price' => 100.0,
                'discount_percentage' => 10.0,
                'offer_price' => 90.0,
                'trademark_id' => NULL,
                'sku' => 'AWR345UY',
                'views_count' => 0,
                'quantity_available' => 200,
                'quantity_sell' => 10,
                'count_alert' => 10,
                'minimum_order' => NULL,
                'taxable' => NULL,
                'approve_status' => 'approve',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2021-12-04 07:39:45',
                'updated_at' => '2022-03-27 16:49:30',
                'deleted_at' => '2022-03-27 16:49:30',
            ),
            1 =>
            array (
                'id' => 13,
                'type' => 'offer_request',
                'deal_id' => NULL,
                'seller_id' => 60,
                'main_category_id' => 1,
                'sub_category_id' => 3,
                'price' => 100.0,
                'discount_percentage' => 10.0,
                'offer_price' => NULL,
                'trademark_id' => NULL,
                'sku' => '243234',
                'views_count' => 0,
                'quantity_available' => 100,
                'quantity_sell' => 0,
                'count_alert' => 3,
                'minimum_order' => 4,
                'taxable' => NULL,
                'approve_status' => 'waiting',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2021-12-08 06:50:53',
                'updated_at' => '2022-03-27 16:49:30',
                'deleted_at' => '2022-03-27 16:49:30',
            ),
            2 =>
            array (
                'id' => 14,
                'type' => 'deals',
                'deal_id' => 1,
                'seller_id' => 0,
                'main_category_id' => 4,
                'sub_category_id' => 9,
                'price' => 100.0,
                'discount_percentage' => 10.0,
                'offer_price' => 90.0,
                'trademark_id' => NULL,
                'sku' => 'AWR345UY',
                'views_count' => 0,
                'quantity_available' => 200,
                'quantity_sell' => 10,
                'count_alert' => 10,
                'minimum_order' => NULL,
                'taxable' => NULL,
                'approve_status' => 'approve',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2021-12-04 07:39:45',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 =>
            array (
                'id' => 15,
                'type' => 'deals',
                'deal_id' => 2,
                'seller_id' => 0,
                'main_category_id' => 1,
                'sub_category_id' => 3,
                'price' => 100.0,
                'discount_percentage' => 10.0,
                'offer_price' => NULL,
                'trademark_id' => NULL,
                'sku' => '243234',
                'views_count' => 0,
                'quantity_available' => 100,
                'quantity_sell' => 0,
                'count_alert' => 3,
                'minimum_order' => 4,
                'taxable' => NULL,
                'approve_status' => 'waiting',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2021-12-08 06:50:53',
                'updated_at' => '2021-12-08 06:50:53',
                'deleted_at' => NULL,
            ),
            4 =>
            array (
                'id' => 16,
                'type' => 'stories',
                'deal_id' => NULL,
                'seller_id' => 60,
                'main_category_id' => 1,
                'sub_category_id' => 3,
                'price' => 100.0,
                'discount_percentage' => 10.0,
                'offer_price' => 90.0,
                'trademark_id' => NULL,
                'sku' => '243234',
                'views_count' => 0,
                'quantity_available' => 100,
                'quantity_sell' => 0,
                'count_alert' => 3,
                'minimum_order' => 4,
                'taxable' => NULL,
                'approve_status' => 'approve',
                'approve_time' => '2022-02-12 14:10:00',
                'status' => 'active',
                'created_at' => '2021-12-30 03:20:53',
                'updated_at' => '2022-03-08 11:11:38',
                'deleted_at' => NULL,
            ),
            5 =>
            array (
                'id' => 17,
                'type' => 'stories',
                'deal_id' => 0,
                'seller_id' => 60,
                'main_category_id' => 4,
                'sub_category_id' => 9,
                'price' => 85.0,
                'discount_percentage' => 0.0,
                'offer_price' => 0.0,
                'trademark_id' => NULL,
                'sku' => 'AWR345UY',
                'views_count' => 3450,
                'quantity_available' => 200,
                'quantity_sell' => 10,
                'count_alert' => 10,
                'minimum_order' => 5,
                'taxable' => NULL,
                'approve_status' => 'approve',
                'approve_time' => '2021-12-28 00:00:00',
                'status' => 'active',
                'created_at' => '2021-12-04 07:39:45',
                'updated_at' => '2022-03-27 16:49:30',
                'deleted_at' => NULL,
            ),
            6 =>
            array (
                'id' => 19,
                'type' => 'stories',
                'deal_id' => NULL,
                'seller_id' => 60,
                'main_category_id' => 3,
                'sub_category_id' => NULL,
                'price' => 50.0,
                'discount_percentage' => 15.0,
                'offer_price' => 35.0,
                'trademark_id' => NULL,
                'sku' => '656456',
                'views_count' => 0,
                'quantity_available' => 10,
                'quantity_sell' => 0,
                'count_alert' => 3,
                'minimum_order' => NULL,
                'taxable' => NULL,
                'approve_status' => 'waiting',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2021-12-30 02:36:25',
                'updated_at' => '2022-02-03 02:49:05',
                'deleted_at' => NULL,
            ),
            7 =>
            array (
                'id' => 21,
                'type' => 'offer_request',
                'deal_id' => NULL,
                'seller_id' => 60,
                'main_category_id' => 2,
                'sub_category_id' => NULL,
                'price' => 100.0,
                'discount_percentage' => 10.0,
                'offer_price' => NULL,
                'trademark_id' => NULL,
                'sku' => '243234',
                'views_count' => 0,
                'quantity_available' => 4,
                'quantity_sell' => 0,
                'count_alert' => 3,
                'minimum_order' => 2,
                'taxable' => NULL,
                'approve_status' => 'waiting',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2022-01-18 01:52:52',
                'updated_at' => '2022-01-18 01:56:12',
                'deleted_at' => '2022-01-18 01:56:12',
            ),
            8 =>
            array (
                'id' => 22,
                'type' => 'offer_request',
                'deal_id' => NULL,
                'seller_id' => 60,
                'main_category_id' => 2,
                'sub_category_id' => 5,
                'price' => 100.0,
                'discount_percentage' => 90.0,
                'offer_price' => NULL,
                'trademark_id' => NULL,
                'sku' => '243234',
                'views_count' => 0,
                'quantity_available' => 20,
                'quantity_sell' => 0,
                'count_alert' => 3,
                'minimum_order' => 4,
                'taxable' => NULL,
                'approve_status' => 'waiting',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2022-01-24 16:37:33',
                'updated_at' => '2022-02-12 13:30:43',
                'deleted_at' => '2022-02-12 13:30:43',
            ),
            9 =>
            array (
                'id' => 23,
                'type' => 'offer_request',
                'deal_id' => NULL,
                'seller_id' => 60,
                'main_category_id' => 2,
                'sub_category_id' => 5,
                'price' => 100.0,
                'discount_percentage' => 20.0,
                'offer_price' => 80.0,
                'trademark_id' => NULL,
                'sku' => '243234',
                'views_count' => 0,
                'quantity_available' => 100,
                'quantity_sell' => 0,
                'count_alert' => 3,
                'minimum_order' => 5,
                'taxable' => NULL,
                'approve_status' => 'waiting',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2022-01-24 16:43:49',
                'updated_at' => '2022-02-05 04:54:16',
                'deleted_at' => '2022-02-05 04:54:16',
            ),
            10 =>
            array (
                'id' => 24,
                'type' => 'offer_request',
                'deal_id' => NULL,
                'seller_id' => 60,
                'main_category_id' => 2,
                'sub_category_id' => 5,
                'price' => 50.0,
                'discount_percentage' => 10.0,
                'offer_price' => 45.0,
                'trademark_id' => NULL,
                'sku' => '243234',
                'views_count' => 0,
                'quantity_available' => 1000,
                'quantity_sell' => 0,
                'count_alert' => 3,
                'minimum_order' => 4,
                'taxable' => 'yes',
                'approve_status' => 'waiting',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2022-01-24 16:46:31',
                'updated_at' => '2022-02-05 04:11:10',
                'deleted_at' => '2022-02-05 04:11:10',
            ),
            11 =>
            array (
                'id' => 25,
                'type' => 'offer_request',
                'deal_id' => NULL,
                'seller_id' => 60,
                'main_category_id' => 1,
                'sub_category_id' => NULL,
                'price' => 100.0,
                'discount_percentage' => 10.0,
                'offer_price' => 90.0,
                'trademark_id' => NULL,
                'sku' => '76567567',
                'views_count' => 0,
                'quantity_available' => 10,
                'quantity_sell' => 0,
                'count_alert' => 3,
                'minimum_order' => 2,
                'taxable' => 'yes',
                'approve_status' => 'waiting',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2022-02-20 09:36:45',
                'updated_at' => '2022-02-20 09:41:31',
                'deleted_at' => '2022-02-20 09:41:31',
            ),
            12 =>
            array (
                'id' => 26,
                'type' => 'offer_request',
                'deal_id' => NULL,
                'seller_id' => 60,
                'main_category_id' => 1,
                'sub_category_id' => NULL,
                'price' => 200.0,
                'discount_percentage' => 10.0,
                'offer_price' => 180.0,
                'trademark_id' => NULL,
                'sku' => '222222',
                'views_count' => 0,
                'quantity_available' => 33,
                'quantity_sell' => 0,
                'count_alert' => 22,
                'minimum_order' => 20,
                'taxable' => NULL,
                'approve_status' => 'waiting',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2022-02-20 09:45:31',
                'updated_at' => '2022-03-08 09:55:13',
                'deleted_at' => '2022-03-08 09:55:13',
            ),
            13 =>
            array (
                'id' => 27,
                'type' => 'offer_request',
                'deal_id' => NULL,
                'seller_id' => 60,
                'main_category_id' => 1,
                'sub_category_id' => 3,
                'price' => 100.0,
                'discount_percentage' => 10.0,
                'offer_price' => 90.0,
                'trademark_id' => NULL,
                'sku' => '233234234',
                'views_count' => 0,
                'quantity_available' => 12,
                'quantity_sell' => 0,
                'count_alert' => 4,
                'minimum_order' => 2,
                'taxable' => 'yes',
                'approve_status' => 'waiting',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2022-03-27 17:01:09',
                'updated_at' => '2022-03-27 17:01:19',
                'deleted_at' => NULL,
            ),
            14 =>
            array (
                'id' => 28,
                'type' => 'offer_request',
                'deal_id' => NULL,
                'seller_id' => 60,
                'main_category_id' => 1,
                'sub_category_id' => 3,
                'price' => 75.0,
                'discount_percentage' => 10.0,
                'offer_price' => 67.5,
                'trademark_id' => NULL,
                'sku' => '242343',
                'views_count' => 0,
                'quantity_available' => 7,
                'quantity_sell' => 0,
                'count_alert' => 5,
                'minimum_order' => 5,
                'taxable' => 'yes',
                'approve_status' => 'waiting',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2022-03-27 17:02:42',
                'updated_at' => '2022-03-27 17:02:42',
                'deleted_at' => NULL,
            ),
            15 =>
            array (
                'id' => 29,
                'type' => 'offer_request',
                'deal_id' => NULL,
                'seller_id' => 60,
                'main_category_id' => 6,
                'sub_category_id' => 3,
                'price' => 60.0,
                'discount_percentage' => NULL,
                'offer_price' => 60.0,
                'trademark_id' => NULL,
                'sku' => '23423423',
                'views_count' => 0,
                'quantity_available' => 8,
                'quantity_sell' => 0,
                'count_alert' => 7,
                'minimum_order' => 1,
                'taxable' => NULL,
                'approve_status' => 'waiting',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2022-03-27 17:07:26',
                'updated_at' => '2022-03-27 17:07:26',
                'deleted_at' => NULL,
            ),
            16 =>
            array (
                'id' => 30,
                'type' => 'offer_request',
                'deal_id' => NULL,
                'seller_id' => 60,
                'main_category_id' => 1,
                'sub_category_id' => 4,
                'price' => 20.0,
                'discount_percentage' => NULL,
                'offer_price' => 20.0,
                'trademark_id' => NULL,
                'sku' => '553434534',
                'views_count' => 0,
                'quantity_available' => 5,
                'quantity_sell' => 0,
                'count_alert' => 4,
                'minimum_order' => 1,
                'taxable' => NULL,
                'approve_status' => 'waiting',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2022-03-27 19:56:07',
                'updated_at' => '2022-03-27 19:56:07',
                'deleted_at' => NULL,
            ),
            17 =>
            array (
                'id' => 31,
                'type' => 'offer_request',
                'deal_id' => NULL,
                'seller_id' => 60,
                'main_category_id' => 2,
                'sub_category_id' => 5,
                'price' => 3.0,
                'discount_percentage' => NULL,
                'offer_price' => 3.0,
                'trademark_id' => NULL,
                'sku' => '31231',
                'views_count' => 0,
                'quantity_available' => 5,
                'quantity_sell' => 0,
                'count_alert' => 1,
                'minimum_order' => 2,
                'taxable' => NULL,
                'approve_status' => 'waiting',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2022-03-27 20:11:47',
                'updated_at' => '2022-03-27 20:12:05',
                'deleted_at' => '2022-03-27 20:12:05',
            ),
            18 =>
            array (
                'id' => 32,
                'type' => 'offer_request',
                'deal_id' => NULL,
                'seller_id' => 60,
                'main_category_id' => 2,
                'sub_category_id' => 5,
                'price' => 3.0,
                'discount_percentage' => NULL,
                'offer_price' => 3.0,
                'trademark_id' => NULL,
                'sku' => '3123',
                'views_count' => 0,
                'quantity_available' => 2,
                'quantity_sell' => 0,
                'count_alert' => 1,
                'minimum_order' => 2,
                'taxable' => NULL,
                'approve_status' => 'waiting',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2022-03-27 20:12:57',
                'updated_at' => '2022-03-27 20:12:57',
                'deleted_at' => NULL,
            ),
            19 =>
            array (
                'id' => 33,
                'type' => 'offer_request',
                'deal_id' => NULL,
                'seller_id' => 60,
                'main_category_id' => 2,
                'sub_category_id' => 5,
                'price' => 2.0,
                'discount_percentage' => NULL,
                'offer_price' => 2.0,
                'trademark_id' => NULL,
                'sku' => '4234',
                'views_count' => 0,
                'quantity_available' => 2,
                'quantity_sell' => 0,
                'count_alert' => 1,
                'minimum_order' => 1,
                'taxable' => NULL,
                'approve_status' => 'waiting',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2022-03-27 20:14:38',
                'updated_at' => '2022-03-27 20:14:38',
                'deleted_at' => NULL,
            ),
            20 =>
            array (
                'id' => 34,
                'type' => 'offer_request',
                'deal_id' => NULL,
                'seller_id' => 60,
                'main_category_id' => 2,
                'sub_category_id' => 5,
                'price' => 3.0,
                'discount_percentage' => NULL,
                'offer_price' => 3.0,
                'trademark_id' => NULL,
                'sku' => 'yyyyy',
                'views_count' => 0,
                'quantity_available' => 6,
                'quantity_sell' => 0,
                'count_alert' => 1,
                'minimum_order' => NULL,
                'taxable' => NULL,
                'approve_status' => 'waiting',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2022-03-27 20:15:38',
                'updated_at' => '2022-03-27 20:15:38',
                'deleted_at' => NULL,
            ),
            21 =>
            array (
                'id' => 35,
                'type' => 'offer_request',
                'deal_id' => NULL,
                'seller_id' => 60,
                'main_category_id' => 2,
                'sub_category_id' => 5,
                'price' => 10.0,
                'discount_percentage' => NULL,
                'offer_price' => 10.0,
                'trademark_id' => NULL,
                'sku' => '32423423',
                'views_count' => 0,
                'quantity_available' => 3,
                'quantity_sell' => 0,
                'count_alert' => 2,
                'minimum_order' => NULL,
                'taxable' => NULL,
                'approve_status' => 'waiting',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2022-03-27 20:18:21',
                'updated_at' => '2022-07-10 11:36:10',
                'deleted_at' => NULL,
            ),
        22 =>
            array (
                'id' => 36,
                'type' => 'offer_request',
                'deal_id' => NULL,
                'seller_id' => 60,
                'main_category_id' => 24,
                'sub_category_id' => 5,
                'price' => 10.0,
                'discount_percentage' => 10,
                'offer_price' => 10.0,
                'trademark_id' => NULL,
                'sku' => '32423423',
                'views_count' => 0,
                'quantity_available' => 3,
                'quantity_sell' => 0,
                'count_alert' => 2,
                'minimum_order' => NULL,
                'taxable' => NULL,
                'approve_status' => 'waiting',
                'approve_time' => NULL,
                'status' => 'active',
                'created_at' => '2022-03-27 20:18:21',
                'updated_at' => '2022-07-10 11:36:10',
                'deleted_at' => NULL,
            ),
        ));


    }
}
